name: "docker-compose-setup"
description: "environment docker-compose setup"

runs:
    using: "composite"
    steps:
        - if: runner.os == 'macOS'
          name: Install Docker on MacOS
          shell: bash
          run: |
              brew update
              docker --version
              brew install docker-compose
              docker-compose --version

#        - if: runner.os == 'Windows'
#          name: Install Docker Compose on Windows
#          shell: pwsh
#          run: |
#              $ErrorActionPreference = "Stop"
#              $dockerComposeVersion = "v2.30.1"
#              $dockerComposePath = "${{ github.workspace }}\docker-compose.exe"
#
#              # 下载 Docker Compose
#              Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-Windows-x86_64.exe" -OutFile $dockerComposePath
#              $dockerComposeDir = [System.IO.Path]::GetDirectoryName($dockerComposePath)
#              [System.Environment]::SetEnvironmentVariable("Path", "$env:Path;$dockerComposeDir", [System.EnvironmentVariableTarget]::Machine)
#              $env:Path += ";$dockerComposeDir"
#              docker --version
#              docker-compose --version

#        - if: runner.os == 'Windows'
#          name: Install Docker Compose on Windows
#          shell: pwsh
#          run: |
#            $ErrorActionPreference = "Stop"
#            $dockerComposeVersion = "v2.30.1"
#            $dockerComposePath = "${{ github.workspace }}\docker-compose.exe"
#            Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-Windows-x86_64.exe" -OutFile $dockerComposePath
#            $dockerComposeDir = [System.IO.Path]::GetDirectoryName($dockerComposePath)
#            [System.Environment]::SetEnvironmentVariable("Path", "$env:Path;$dockerComposeDir", [System.EnvironmentVariableTarget]::Machine)
#
#            $env:Path += ";$dockerComposeDir"
#            chmod +x $dockerComposePath
#
#            docker --version
#            docker-compose --version

#        - if: runner.os == 'Windows'
#          name: Test Docker Compose
#          shell: bash
#          run: |
#            echo $env:Path
#            echo "test docker-compose"
#            docker -v
#            docker-compose -v

        - if: runner.os == 'Windows'
          name: Install Docker Compose
          shell: wsl-run {0}
          run: |
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            sudo apt update
            sudo apt install docker-ce docker-ce-cli containerd.io
            docker --version
            DOCKER_COMPOSE_VERSION=v2.30.1
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

        - if: runner.os == 'Linux'
          name: Install Docker Compose
          shell: bash
          run: |
            DOCKER_COMPOSE_VERSION=v2.30.1
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
